In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , classification_report, confusion_matrix

In [ ]:
df = pd.read_csv("/content/loan_data.csv")

In [ ]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [ ]:
df.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

In [ ]:
df['person_gender'].unique()

array(['female', 'male'], dtype=object)

In [ ]:
df['person_gender'].nunique()

2

In [ ]:
df['person_gender'].value_counts()

person_gender
male      24841
female    20159
Name: count, dtype: int64

In [ ]:
df['person_education'].unique()

array(['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate'],
      dtype=object)

In [ ]:
df['person_education'].nunique()

5

In [ ]:
df['person_education'].value_counts()

person_education
Bachelor       13399
Associate      12028
High School    11972
Master          6980
Doctorate        621
Name: count, dtype: int64

In [ ]:
df['loan_percent_income'].unique()

array([0.49, 0.08, 0.44, 0.53, 0.19, 0.37, 0.35, 0.13, 0.34, 0.3 , 0.27,
       0.25, 0.05, 0.24, 0.31, 0.26, 0.12, 0.18, 0.21, 0.43, 0.11, 0.4 ,
       0.32, 0.1 , 0.41, 0.22, 0.07, 0.02, 0.17, 0.51, 0.38, 0.33, 0.06,
       0.03, 0.28, 0.04, 0.09, 0.2 , 0.23, 0.15, 0.48, 0.5 , 0.14, 0.42,
       0.01, 0.46, 0.29, 0.39, 0.36, 0.16, 0.  , 0.57, 0.45, 0.52, 0.55,
       0.61, 0.62, 0.66, 0.54, 0.47, 0.56, 0.58, 0.63, 0.59])

In [ ]:
df['loan_percent_income'].nunique()

64

In [ ]:
df['loan_percent_income'].value_counts()

loan_percent_income
0.08    2593
0.10    2421
0.07    2415
0.09    2295
0.06    2242
        ...
0.57       1
0.66       1
0.58       1
0.63       1
0.59       1
Name: count, Length: 64, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
smote = SMOTE(random_state=42)

In [ ]:
df['loan_status'].unique()

array([1, 0])

In [ ]:
df['loan_status'].nunique()

2

In [ ]:
df['loan_status'].value_counts()

loan_status
0    35000
1    10000
Name: count, dtype: int64

In [ ]:
x = df.drop('loan_status', axis=1)
y = df['loan_status']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
x_train_encoded = pd.get_dummies(x_train, columns=categorical_cols, drop_first=True)
x_test_encoded = pd.get_dummies(x_test, columns=categorical_cols, drop_first=True)

In [ ]:


x_train_resampled, y_train_resampled = smote.fit_resample(x_train_encoded, y_train)

In [ ]:
df_resampled = pd.concat([x_train_resampled, y_train_resampled], axis=1)

In [ ]:
df_resampled.head()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,loan_status
0,34.0,97265.0,11,15000.0,12.73,0.15,9.0,631,False,True,...,False,False,False,False,False,False,True,False,False,0
1,25.0,72953.0,3,12000.0,11.86,0.16,4.0,659,True,False,...,False,False,True,False,False,False,False,True,True,0
2,41.0,322597.0,18,24000.0,10.37,0.07,11.0,683,False,False,...,False,False,False,False,False,False,True,False,True,0
3,27.0,94232.0,4,9600.0,17.14,0.10,7.0,641,True,False,...,False,False,True,True,False,False,False,False,False,0
4,27.0,84873.0,7,7059.0,12.97,0.08,3.0,706,True,False,...,False,False,True,False,True,False,False,False,True,0

In [ ]:
df_resampled['loan_status'].value_counts()

loan_status
0    28010
1    28010
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
df_resampled_scaled = scaler.fit_transform(df_resampled)

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=2)

In [ ]:
df_pca = pca.fit_transform(df_resampled_scaled)

In [ ]:
df_pca.shape

(56020, 2)

In [ ]:
df_resampled.shape

(56020, 23)